<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net7.0;net6.0;netstandard2.1;net48</TargetFrameworks>
    <RootNamespace>NCoreUtils.Data.Protocol</RootNamespace>
    <ImplcitUsings>enable</ImplcitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\shared\CommonFunctionNames.cs" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' Or $(TargetFramework.StartsWith('net4')) ">
    <Compile Include="..\shared\CodeAnalysis\**" />
  </ItemGroup>
  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <Compile Include="..\shared\Ranges\**" />
    <Compile Include="..\shared\CodeAnalysis.NetFramework\**" />
  </ItemGroup>
  <ItemGroup Condition="!$(TargetFramework.StartsWith('net4'))">
    <Compile Remove="*.NetFramework.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NCoreUtils.Data.Protocol.CombinatorParser\NCoreUtils.Data.Protocol.CombinatorParser.csproj" />
    <ProjectReference Include="..\NCoreUtils.Data.Protocol.TypeInference\NCoreUtils.Data.Protocol.TypeInference.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(FxNugetVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(FxNugetVersion)" />
  </ItemGroup>
</Project>
