<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;net6.0;netstandard2.1;net48</TargetFrameworks>
    <RootNamespace>NCoreUtils.Data.Protocol</RootNamespace>
  </PropertyGroup>
  <!-- NOTE: NET Standard/NET Framework polyfills -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' Or $(TargetFramework.StartsWith('net4')) ">
    <Compile Include="..\shared\CodeAnalysis\**" />
    <Compile Include="..\shared\CompilerServices\**" />
  </ItemGroup>
  <!-- NOTE: NET Framework polyfills -->
  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <Compile Include="..\shared\CodeAnalysis.NetFramework\**" />
    <Compile Include="..\shared\Ranges\**" />
  </ItemGroup>
  <!-- NOTE: Common -->
  <ItemGroup>
    <Compile Include="..\shared\Check.cs" />
    <ProjectReference Include="..\NCoreUtils.Data.Protocol.Abstractions\NCoreUtils.Data.Protocol.Abstractions.csproj" />
  </ItemGroup>
</Project>
