// Implementation file for parser generated by fsyacc
module NCoreUtils.Data.Protocol.Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"

open NCoreUtils.Data.Protocol.Ast
open System.Collections.Immutable

# 11 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | LPAREN
  | RPAREN
  | COMMA
  | OR
  | AND
  | EQ
  | NEQ
  | GT
  | GE
  | LT
  | LE
  | VALUE of (string)
  | IDENT of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_LPAREN
    | TOKEN_RPAREN
    | TOKEN_COMMA
    | TOKEN_OR
    | TOKEN_AND
    | TOKEN_EQ
    | TOKEN_NEQ
    | TOKEN_GT
    | TOKEN_GE
    | TOKEN_LT
    | TOKEN_LE
    | TOKEN_VALUE
    | TOKEN_IDENT
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_expr
    | NONTERM_andor
    | NONTERM_binop
    | NONTERM_valueexpr
    | NONTERM_args

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | LPAREN  -> 1 
  | RPAREN  -> 2 
  | COMMA  -> 3 
  | OR  -> 4 
  | AND  -> 5 
  | EQ  -> 6 
  | NEQ  -> 7 
  | GT  -> 8 
  | GE  -> 9 
  | LT  -> 10 
  | LE  -> 11 
  | VALUE _ -> 12 
  | IDENT _ -> 13 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_LPAREN 
  | 2 -> TOKEN_RPAREN 
  | 3 -> TOKEN_COMMA 
  | 4 -> TOKEN_OR 
  | 5 -> TOKEN_AND 
  | 6 -> TOKEN_EQ 
  | 7 -> TOKEN_NEQ 
  | 8 -> TOKEN_GT 
  | 9 -> TOKEN_GE 
  | 10 -> TOKEN_LT 
  | 11 -> TOKEN_LE 
  | 12 -> TOKEN_VALUE 
  | 13 -> TOKEN_IDENT 
  | 16 -> TOKEN_end_of_input
  | 14 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_expr 
    | 3 -> NONTERM_expr 
    | 4 -> NONTERM_expr 
    | 5 -> NONTERM_expr 
    | 6 -> NONTERM_andor 
    | 7 -> NONTERM_andor 
    | 8 -> NONTERM_binop 
    | 9 -> NONTERM_binop 
    | 10 -> NONTERM_binop 
    | 11 -> NONTERM_binop 
    | 12 -> NONTERM_binop 
    | 13 -> NONTERM_binop 
    | 14 -> NONTERM_valueexpr 
    | 15 -> NONTERM_valueexpr 
    | 16 -> NONTERM_valueexpr 
    | 17 -> NONTERM_args 
    | 18 -> NONTERM_args 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 16 
let _fsyacc_tagOfErrorTerminal = 14

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | LPAREN  -> "LPAREN" 
  | RPAREN  -> "RPAREN" 
  | COMMA  -> "COMMA" 
  | OR  -> "OR" 
  | AND  -> "AND" 
  | EQ  -> "EQ" 
  | NEQ  -> "NEQ" 
  | GT  -> "GT" 
  | GE  -> "GE" 
  | LT  -> "LT" 
  | LE  -> "LE" 
  | VALUE _ -> "VALUE" 
  | IDENT _ -> "IDENT" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | LPAREN  -> (null : System.Object) 
  | RPAREN  -> (null : System.Object) 
  | COMMA  -> (null : System.Object) 
  | OR  -> (null : System.Object) 
  | AND  -> (null : System.Object) 
  | EQ  -> (null : System.Object) 
  | NEQ  -> (null : System.Object) 
  | GT  -> (null : System.Object) 
  | GE  -> (null : System.Object) 
  | LT  -> (null : System.Object) 
  | LE  -> (null : System.Object) 
  | VALUE _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | IDENT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 6us; 65535us; 0us; 2us; 9us; 5us; 10us; 6us; 11us; 7us; 22us; 8us; 26us; 8us; 5us; 65535us; 2us; 10us; 5us; 10us; 6us; 10us; 7us; 10us; 8us; 10us; 5us; 65535us; 2us; 9us; 5us; 9us; 6us; 9us; 7us; 9us; 8us; 9us; 6us; 65535us; 0us; 4us; 9us; 4us; 10us; 4us; 11us; 4us; 22us; 4us; 26us; 4us; 2us; 65535us; 22us; 23us; 26us; 27us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 10us; 16us; 22us; 29us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 3us; 1us; 3us; 4us; 1us; 1us; 1us; 2us; 3us; 3us; 3us; 4us; 3us; 3us; 4us; 4us; 3us; 3us; 4us; 5us; 4us; 3us; 4us; 17us; 18us; 1us; 3us; 1us; 4us; 1us; 5us; 1us; 5us; 1us; 6us; 1us; 7us; 1us; 8us; 1us; 9us; 1us; 10us; 1us; 11us; 1us; 12us; 1us; 13us; 2us; 14us; 15us; 1us; 14us; 1us; 14us; 1us; 14us; 1us; 16us; 1us; 17us; 1us; 17us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 8us; 10us; 12us; 16us; 20us; 24us; 29us; 31us; 33us; 35us; 37us; 39us; 41us; 43us; 45us; 47us; 49us; 51us; 53us; 56us; 58us; 60us; 62us; 64us; 66us; |]
let _fsyacc_action_rows = 28
let _fsyacc_actionTableElements = [|3us; 32768us; 1us; 11us; 12us; 25us; 13us; 21us; 0us; 49152us; 9us; 32768us; 0us; 3us; 4us; 14us; 5us; 13us; 6us; 15us; 7us; 16us; 8us; 17us; 9us; 19us; 10us; 18us; 11us; 20us; 0us; 16385us; 0us; 16386us; 6us; 16387us; 6us; 15us; 7us; 16us; 8us; 17us; 9us; 19us; 10us; 18us; 11us; 20us; 8us; 16388us; 4us; 14us; 5us; 13us; 6us; 15us; 7us; 16us; 8us; 17us; 9us; 19us; 10us; 18us; 11us; 20us; 9us; 32768us; 2us; 12us; 4us; 14us; 5us; 13us; 6us; 15us; 7us; 16us; 8us; 17us; 9us; 19us; 10us; 18us; 11us; 20us; 9us; 16402us; 3us; 26us; 4us; 14us; 5us; 13us; 6us; 15us; 7us; 16us; 8us; 17us; 9us; 19us; 10us; 18us; 11us; 20us; 3us; 32768us; 1us; 11us; 12us; 25us; 13us; 21us; 3us; 32768us; 1us; 11us; 12us; 25us; 13us; 21us; 3us; 32768us; 1us; 11us; 12us; 25us; 13us; 21us; 0us; 16389us; 0us; 16390us; 0us; 16391us; 0us; 16392us; 0us; 16393us; 0us; 16394us; 0us; 16395us; 0us; 16396us; 0us; 16397us; 1us; 16399us; 1us; 22us; 3us; 32768us; 1us; 11us; 12us; 25us; 13us; 21us; 1us; 32768us; 2us; 24us; 0us; 16398us; 0us; 16400us; 3us; 32768us; 1us; 11us; 12us; 25us; 13us; 21us; 0us; 16401us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 4us; 5us; 15us; 16us; 17us; 24us; 33us; 43us; 53us; 57us; 61us; 65us; 66us; 67us; 68us; 69us; 70us; 71us; 72us; 73us; 74us; 76us; 80us; 82us; 83us; 84us; 88us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 1us; 3us; 3us; 3us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 4us; 1us; 1us; 3us; 1us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 2us; 2us; 3us; 3us; 4us; 4us; 4us; 4us; 4us; 4us; 5us; 5us; 5us; 6us; 6us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 16386us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16389us; 16390us; 16391us; 16392us; 16393us; 16394us; 16395us; 16396us; 16397us; 65535us; 65535us; 65535us; 16398us; 16400us; 65535us; 16401us; |]
let _fsyacc_reductions ()  =    [| 
# 168 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data :  Node )) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 177 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 23 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                    _1 
                   )
# 23 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 :  Node ));
# 188 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'valueexpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 26 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                     _1 
                   )
# 26 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'expr));
# 199 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'binop)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 27 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                                        Binary(_1, _2, _3) 
                   )
# 27 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'expr));
# 212 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'andor)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 28 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                                            Binary(_1, _2, _3) 
                   )
# 28 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'expr));
# 225 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                              _2 
                   )
# 29 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'expr));
# 236 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                BinaryOperation.AndAlso 
                   )
# 32 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'andor));
# 246 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                BinaryOperation.OrElse 
                   )
# 33 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'andor));
# 256 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                BinaryOperation.Equal 
                   )
# 36 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'binop));
# 266 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                BinaryOperation.NotEqual 
                   )
# 37 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'binop));
# 276 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                BinaryOperation.GreaterThan 
                   )
# 38 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'binop));
# 286 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                BinaryOperation.LessThan 
                   )
# 39 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'binop));
# 296 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 40 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                BinaryOperation.GreaterThanOrEqual 
                   )
# 40 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'binop));
# 306 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 41 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                BinaryOperation.LessThanOrEqual 
                   )
# 41 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'binop));
# 316 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'args)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 44 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                                    Call (_1, ImmutableArray.CreateRange _3) 
                   )
# 44 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'valueexpr));
# 328 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 45 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                 Identifier _1 
                   )
# 45 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'valueexpr));
# 339 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 46 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                 Constant _1 
                   )
# 46 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'valueexpr));
# 350 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'args)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 49 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                           _1 :: _3 
                   )
# 49 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'args));
# 362 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 50 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                                [ _1 ] 
                   )
# 50 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fsy"
                 : 'args));
|]
# 374 "/home/artyom/Projects/NCoreUtils.Data.Protocol/NCoreUtils.Data.Protocol/Parser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 17;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf :  Node  =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
